import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    apple: "/favicon-32x32.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const webSDKVersion = process.env.NEXT_PUBLIC_WEB_SDK_VERSION;
  const cdnUrl = `https://cdn.cloud.pspdfkit.com/pspdfkit-web@${webSDKVersion}/nutrient-viewer.js`;

  return (
    <html lang="en">
      <head>
        {/* DNS prefetch and preconnect for faster CDN connection */}
        <link rel="dns-prefetch" href="//cdn.cloud.pspdfkit.com" />
        <link
          rel="preconnect"
          href="https://cdn.cloud.pspdfkit.com"
          crossOrigin=""
        />

        {/* Preload the script to start downloading immediately */}
        <link rel="preload" href={cdnUrl} as="script" crossOrigin="" />

        {/* Load the script before page becomes interactive */}
        <Script src={cdnUrl} strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
